"""Convert Unreal's native T3D graph export to searchable node/pin evidence.

Retains links: a pin default is not an effective value if that pin is connected.
The native T3D files remain the authoritative export.
"""
import json
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parent

def quoted(line, key):
    match = re.search(r'(?:^|[, (])' + re.escape(key) + r'="((?:\\.|[^"\\])*)"', line)
    return match.group(1) if match else None

def parse(path):
    stack, nodes = [], []
    for number, raw in enumerate(path.read_text(encoding="utf-8-sig").splitlines(), 1):
        line = raw.strip()
        if line.startswith("Begin Object"):
            stack.append({"name": quoted(line, "Name"), "path": quoted(line, "ExportPath"), "line": number, "properties": {}, "pins": []})
        elif line == "End Object":
            obj = stack.pop()
            if obj["pins"]:
                obj["graph"] = stack[-1]["name"] if stack else None
                nodes.append(obj)
        elif stack:
            if line.startswith("CustomProperties Pin"):
                pin = {key: quoted(line, key) for key in ("PinName", "DefaultValue", "AutogeneratedDefaultValue", "DefaultObject", "PinType.PinCategory")}
                pin["PinId"] = re.search(r"PinId=([0-9A-F]+)", line).group(1)
                pin["direction"] = "output" if 'Direction="EGPD_Output"' in line else "input"
                links = re.search(r"LinkedTo=\(([^)]*)\)", line)
                pin["links"] = [x.strip().split() for x in links.group(1).split(",") if x.strip()] if links else []
                pin["line"] = number
                pin["orphaned"] = "bOrphanedPin=True" in line
                stack[-1]["pins"].append({k: v for k, v in pin.items() if v is not None})
            elif "=" in line:
                key, value = line.split("=", 1)
                if key in ("FunctionReference", "VariableReference", "NodeComment", "Enum", "FunctionName", "MacroGraphReference", "EnabledState", "CustomFunctionName"):
                    stack[-1]["properties"][key] = value
    return nodes

def main(label):
    out = ROOT / "derived" / label
    out.mkdir(parents=True, exist_ok=True)
    for path in (ROOT / "raw" / label).glob("*.t3d"):
        if "_defaults" in path.stem or not path.stem.startswith(("BP_", "BFL_")):
            continue
        nodes = parse(path)
        if nodes:
            (out / (path.stem + ".json")).write_text(json.dumps(nodes, indent=2), encoding="utf-8")
            text = []
            for n in nodes:
                text.append(f'{n["graph"]}/{n["name"]} [T3D:{n["line"]}] {n["properties"]}')
                for p in n["pins"]:
                    if p["PinName"] == "self" and not p["links"]:
                        continue
                    text.append("  " + p["direction"] + " " + p["PinName"] + " = " + str(p.get("DefaultValue", p.get("DefaultObject", ""))) + " links=" + str(p["links"]))
            (out / (path.stem + ".txt")).write_text("\n".join(text), encoding="utf-8")
    print("Summarized", label)

if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "current")
